using System.Diagnostics;
using System.Text;
using ModelContextProtocol.Client;
using workflowX.Infrastructure;

sealed class GitHubMcpAdapter
{
    private readonly McpClient? _client;
    private readonly bool _autoCreatePullRequest;
    private readonly string _baseBranch;

    public GitHubMcpAdapter(McpClient? client, bool autoCreatePullRequest, string baseBranch)
    {
        _client = client;
        _autoCreatePullRequest = autoCreatePullRequest;
        _baseBranch = string.IsNullOrWhiteSpace(baseBranch) ? "main" : baseBranch;
    }

    public Task PublishStatusAsync(string message)
    {
        // Wire to concrete MCP tools as needed; this keeps orchestration isolated from MCP details.
        Console.WriteLine($"[MCP Status] {message}");
        return Task.CompletedTask;
    }

    public string EnsureFeatureBranch(WorkflowState state)
    {
        if (!Directory.Exists(Path.Combine(state.RepoPath, ".git")))
        {
            Console.WriteLine("[Git] Warning: not a git repository; staying on current branch.");
            return string.Empty;
        }

        string desiredBranch = ResolveUniqueBranchName(
            state.RepoPath,
            WorkflowTaskNaming.ResolveFeatureBranchName(state));

        if (!string.IsNullOrWhiteSpace(state.FeatureBranchName)
            && !string.Equals(state.FeatureBranchName, desiredBranch, StringComparison.OrdinalIgnoreCase)
            && !BranchExists(state.RepoPath, desiredBranch))
        {
            string previousBranch = state.FeatureBranchName;
            CheckoutBranch(state.RepoPath, desiredBranch, createIfMissing: true);
            state.FeatureBranchName = desiredBranch;
            Console.WriteLine($"[Git] Renamed feature branch {previousBranch} -> {desiredBranch}");
            LogCurrentBranch(state.RepoPath);
            return desiredBranch;
        }

        if (!string.IsNullOrWhiteSpace(state.FeatureBranchName))
        {
            CheckoutBranch(state.RepoPath, state.FeatureBranchName, createIfMissing: false);
            LogCurrentBranch(state.RepoPath);
            return state.FeatureBranchName;
        }

        CheckoutBranch(state.RepoPath, desiredBranch, createIfMissing: true);
        state.FeatureBranchName = desiredBranch;
        Console.WriteLine($"[Git] Created and switched to feature branch: {desiredBranch}");
        LogCurrentBranch(state.RepoPath);
        return desiredBranch;
    }

    public async Task PublishPullRequestAsync(WorkflowState state, CancellationToken cancellationToken = default)
    {
        if (!_autoCreatePullRequest)
        {
            state.PullRequestStatus = "PR creation disabled by configuration.";
            return;
        }

        if (!Directory.Exists(Path.Combine(state.RepoPath, ".git")))
        {
            state.PullRequestStatus = "Repository is not a git working tree; cannot create PR.";
            return;
        }

        try
        {
            if (!IsCommandAvailable("gh"))
            {
                state.PullRequestStatus = "GitHub CLI (`gh`) is not installed or not available in PATH.";
                return;
            }

            string reportPath = WriteWorkflowReport(state);
            string branchName = EnsureFeatureBranch(state);
            if (string.IsNullOrWhiteSpace(branchName))
            {
                branchName = ResolveUniqueBranchName(
                    state.RepoPath,
                    WorkflowTaskNaming.ResolveFeatureBranchName(state));
                CheckoutBranch(state.RepoPath, branchName, createIfMissing: true);
                state.FeatureBranchName = branchName;
            }
            RunCommand("git", $"-C \"{state.RepoPath}\" add \"{reportPath}\"");

            string commitTitle = $"chore: add workflow report for {WorkflowTaskNaming.ToBranchSlug(state.Task.Title)}";
            string commitBody = "Generated by multi-agent workflow orchestrator.";
            RunCommand(
                "git",
                $"-C \"{state.RepoPath}\" -c user.name=\"workflowX\" -c user.email=\"workflowX@local\" commit -m \"{Escape(commitTitle)}\" -m \"{Escape(commitBody)}\"");
            RunCommand("git", $"-C \"{state.RepoPath}\" push -u origin {branchName}");

            string prTitle = $"[Auto] {state.Task.Title}";
            string prBody = BuildPrBody(state);
            string tempBodyPath = Path.GetTempFileName();
            await File.WriteAllTextAsync(tempBodyPath, prBody, cancellationToken);

            try
            {
            var output = RunCommand(
                "gh",
                $"pr create --title \"{Escape(prTitle)}\" --body-file \"{tempBodyPath}\" --base \"{_baseBranch}\" --head \"{branchName}\"",
                state.RepoPath);

            string? url = output.StdOut
                .Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries)
                .FirstOrDefault(line => line.StartsWith("http", StringComparison.OrdinalIgnoreCase));

            if (!string.IsNullOrWhiteSpace(url))
            {
                state.PullRequestUrl = url.Trim();
                state.PullRequestStatus = "Pull request created.";
            }
            else
            {
                state.PullRequestStatus = "PR command completed but URL not detected.";
            }
            }
            finally
            {
                if (File.Exists(tempBodyPath))
                {
                    File.Delete(tempBodyPath);
                }
            }
        }
        catch (Exception ex)
        {
            state.PullRequestStatus = $"PR automation failed: {ex.Message}";
        }
    }

    static string WriteWorkflowReport(WorkflowState state)
    {
        string reportDirectory = Path.Combine(state.RepoPath, "workflowX-output");
        Directory.CreateDirectory(reportDirectory);
        string fileName = $"workflow-report-{DateTimeOffset.UtcNow:yyyyMMdd-HHmmss}.md";
        string fullPath = Path.Combine(reportDirectory, fileName);

        var content = new StringBuilder();
        content.AppendLine($"# Workflow Report - {state.Task.Title}");
        content.AppendLine();
        content.AppendLine($"- Stage: {state.Stage}");
        content.AppendLine($"- Task: {state.Task.Description}");
        content.AppendLine();
        content.AppendLine("## Agent Summaries");
        content.AppendLine();
        content.AppendLine($"- Architecture: {state.Architecture?.Summary}");
        content.AppendLine($"- Backend: {state.Backend?.Summary}");
        content.AppendLine($"- Frontend: {state.Frontend?.Summary}");
        content.AppendLine($"- Observer: {state.Observer?.Summary}");
        content.AppendLine($"- Auditor: {state.Audit?.Summary}");
        if (state.Recovery is not null)
        {
            content.AppendLine($"- Recovery: {state.Recovery.Summary}");
        }
        content.AppendLine();
        content.AppendLine("## Timeline");
        foreach (var line in state.Timeline)
        {
            content.AppendLine($"- {line}");
        }

        File.WriteAllText(fullPath, content.ToString());
        return fullPath;
    }

    static string BuildPrBody(WorkflowState state)
    {
        return $"""
            ## Summary
            - Automated workflow execution for: {state.Task.Title}
            - Final stage: {state.Stage}
            - Recovery attempts: {state.RecoveryAttemptCount}

            ## Workflow outputs
            - Architecture: {state.Architecture?.Summary}
            - Backend: {state.Backend?.Summary}
            - Frontend: {state.Frontend?.Summary}
            - Observer: {state.Observer?.Summary}
            - Auditor: {state.Audit?.Summary}

            ## Test Plan
            - [ ] Review generated workflow report
            - [ ] Validate code changes and run unit/integration tests
            - [ ] Perform manual QA for impacted user flows
            """;
    }

    static string ResolveUniqueBranchName(string repoPath, string preferredBranchName)
    {
        if (!BranchExists(repoPath, preferredBranchName))
        {
            return preferredBranchName;
        }

        for (int suffix = 2; suffix < 100; suffix++)
        {
            string candidate = $"{preferredBranchName}-{suffix}";
            if (!BranchExists(repoPath, candidate))
            {
                return candidate;
            }
        }

        return $"{preferredBranchName}-{DateTimeOffset.UtcNow:yyyyMMddHHmmss}";
    }

    static bool BranchExists(string repoPath, string branchName) =>
        GitCommandRunner.TryRun($"-C \"{repoPath}\" show-ref --verify --quiet refs/heads/{branchName}", out _, out _);

    static void CheckoutBranch(string repoPath, string branchName, bool createIfMissing)
    {
        if (createIfMissing)
        {
            if (BranchExists(repoPath, branchName))
            {
                RunCommand("git", $"-C \"{repoPath}\" checkout {branchName}");
            }
            else
            {
                RunCommand("git", $"-C \"{repoPath}\" checkout -b {branchName}");
            }

            return;
        }

        RunCommand("git", $"-C \"{repoPath}\" checkout {branchName}");
    }

    static void LogCurrentBranch(string repoPath)
    {
        if (!GitCommandRunner.TryRun($"-C \"{repoPath}\" branch --show-current", out string current, out _))
        {
            return;
        }

        string branch = current.Trim();
        if (!string.IsNullOrWhiteSpace(branch))
        {
            Console.WriteLine($"[Git] Current branch: {branch}");
        }
    }

    static string Escape(string value) => value.Replace("\"", "\\\"");

    static bool IsCommandAvailable(string commandName)
    {
        string checker = OperatingSystem.IsWindows() ? "where" : "which";
        try
        {
            var result = RunCommand(checker, commandName);
            return !string.IsNullOrWhiteSpace(result.StdOut);
        }
        catch
        {
            return false;
        }
    }

    static CommandResult RunCommand(string fileName, string arguments, string? workingDirectory = null)
    {
        var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = fileName,
                Arguments = arguments,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            }
        };

        if (!string.IsNullOrWhiteSpace(workingDirectory))
        {
            process.StartInfo.WorkingDirectory = workingDirectory;
        }

        process.Start();
        string stdout = process.StandardOutput.ReadToEnd();
        string stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();

        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"Command failed: {fileName} {arguments}\n{stdout}\n{stderr}");
        }

        return new CommandResult(stdout, stderr);
    }

    readonly record struct CommandResult(string StdOut, string StdErr);
}
